name: Feature request
description: Suggest a useful improvement
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested behavior and alternatives
